#pragma config(Motor,  port2,           rightMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           clawAngleMotor, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           grabMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	//Autonomous
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;
	motor[grabMotor] = 20;
	motor[clawAngleMotor] = 0;

	wait1Msec(2000);

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;

	wait1Msec(500);
	motor[grabMotor] = -20;

	wait1Msec(250);

	motor[clawAngleMotor] = 45;
	motor[leftMotor] = -50;
	motor[rightMotor] = 50;
	wait1Msec(1000);

	motor[clawAngleMotor] = 17;
	motor[leftMotor] = 50;
	wait1Msec(1250);

	motor[grabMotor] = 20;
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[clawAngleMotor] = 0;

	wait1Msec(500);

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[grabMotor] = -60;
	motor[clawAngleMotor] = 0;

	wait10Msec(500)
	motor[grabMotor] = 0

	*/

	while(true)
	{


		bool clawUpSet = true;

		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];


		if(vexRT[Btn5U]==1)
		{
			motor[clawAngleMotor] = 127;
		}
		else if(vexRT[Btn5D]==1)
		{
			motor[clawAngleMotor] = -127;
		}
		else
		{
			if(clawUpSet == true)
			{
				motor[clawAngleMotor] = 17;
			}
			else
			{
				motor[clawAngleMotor] = 0;
			}
		}

		if(vexRT[Btn8L]==1)
		{
			if(clawUpSet == true)
			{
				clawUpSet = false;
			}
			else
			{
				clawUpSet = true;
			}
		}

		if(vexRT[Btn7R]==1)
		{
			//Autonomous
			motor[leftMotor] = 50;
			motor[rightMotor] = 50;
			motor[grabMotor] = 20;
			motor[clawAngleMotor] = 0;

			wait1Msec(2000);

			motor[rightMotor] = 0;
			motor[leftMotor] = 0;

			wait1Msec(500);
			motor[grabMotor] = -20;

			wait1Msec(250);

			motor[clawAngleMotor] = 45;
			motor[leftMotor] = -50;
			motor[rightMotor] = 50;
			wait1Msec(1000);

			motor[clawAngleMotor] = 17;
			motor[leftMotor] = 50;
			wait1Msec(1250);

			motor[grabMotor] = 20;
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			motor[clawAngleMotor] = 0;

			wait1Msec(500);

			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			motor[grabMotor] = -60;
			motor[clawAngleMotor] = 0;

			wait10Msec(500)
			motor[grabMotor] = 0
		}

		if(vexRT[Btn6U]==1)
		{
			motor[grabMotor] = 127;
		}
		else if(vexRT[Btn6D]==1)
		{
			motor[grabMotor] = -127;
		}
		else
		{
			motor[grabMotor] = 0;
		}





	}

}
